# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
#app.cors_listener:
#    class:      AppBundle\Listener\CorsListener
#    tags:
#       - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
